# Generated by Django 3.2.25 on 2025-01-07 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Título do vídeo', max_length=255)),
                ('file', models.FileField(help_text='Arquivo de vídeo no formato MP4', upload_to='videos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, help_text='Data de upload do vídeo')),
            ],
        ),
    ]
